print("Hello World")
print("Day 1- What to Print")
print("Hello World!/nHello World!")
print("Hello"+"Angela")
print("Hello" + "Angela")
input("What is your name?")
print("Hello"+input("What is your name?"))
